#Project version = 1.0
version: '2.2'

services:
    web:
        image: webjump/nginx:alpine
        env_file:
            - ./config.env
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./logs/nginx:/var/log/nginx
            - ./config/nginx:/etc/nginx
            - ./web:/var/www/html
            - ./scripts/nginx-config.sh:/usr/local/bin/nginx-config.sh
        depends_on:
            - php
        command: sh -c "chmod +x /usr/local/bin/scripts/nginx-conf.sh && nginx-config.sh"
        networks:
            - front
            - back

    php:
        image: webjump/php:latest
        env_file:
            - ./config.env
        volumes:
            - ./logs/php:/var/log/php
            - ./logs/php/xdebug/:/var/log/php
            - ./config/magento/php.ini.sample:/usr/local/etc/php/php.ini
            - ./config/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./config/php/conf.d/php.ini:/usr/local/etc/php/conf.d/docker-php-ext-error.ini
            - ./config/php/fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./config/php/bin/magento:/usr/local/bin/magento
            - ./web:/var/www/html
        depends_on:
            - database
            - cache
            - session
        user: www-data
        networks:
            - back

    database:
        image: percona:5.7.19
        working_dir: /dump
        env_file:
            - ./config.env
        ports:
            - 3306:3306
        volumes:
            - database_data:/var/lib/mysql
            - ./dump:/dump
        networks:
            - back

    cache:
        image: redis:alpine
        env_file:
            - ./config.env
        networks:
            - back

    session:
        image: redis:alpine
        env_file:
            - ./config.env
        networks:
            - back

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        env_file:
            - ./config.env
        ports:
            - 8080:80
        networks:
            - front
            - back

networks:
    front:
        driver: bridge
    back:
        driver: bridge

volumes:
    database_data:
        driver: local
